# -*- coding: utf-8 -*-
"""Data Cleaning & Structural Validation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rJFFAD5U9JliG-2a8SOeQyReRFDn7VmF
"""

import pandas as pd
import re

# Load dataset
# Correcting the file path to '/content/raw_data.txt'
df = pd.read_csv("/content/raw_data.txt")

print("=" * 50)
print("ORIGINAL DATA")
print("=" * 50)
print(df)

# -----------------------------
# STEP 1: Handle Missing Values
# -----------------------------

# Fill missing Age with mean age
df["Age"] = df["Age"].fillna(df["Age"].mean())

# Fill missing Email with placeholder
df["Email"] = df["Email"].fillna("unknown@example.com")

# -----------------------------
# STEP 2: Standardize Text Data
# -----------------------------

# Standardize city names
df["City"] = df["City"].str.title()

# Remove extra spaces from Name column
df["Name"] = df["Name"].str.strip()

# -----------------------------
# STEP 3: Remove Duplicate Records
# -----------------------------

df = df.drop_duplicates(
    subset=["Name", "Age", "Email", "City"]
)

# -----------------------------
# STEP 4: Validate Email Format
# -----------------------------

def validate_email(email):
    pattern = r'^[\w\.-]+@[\w\.-]+\.\w+$'
    return bool(re.match(pattern, str(email)))

df["Email_Valid"] = df["Email"].apply(validate_email)

# -----------------------------
# STEP 5: Structural Validation
# -----------------------------

# Check for missing values
missing_values = df.isnull().sum()

print("\n" + "=" * 50)
print("MISSING VALUES AFTER CLEANING")
print("=" * 50)
print(missing_values)

# -----------------------------
# STEP 6: Save Cleaned Dataset
# -----------------------------

df.to_csv("cleaned_data.csv", index=False)

# -----------------------------
# FINAL OUTPUT
# -----------------------------

print("\n" + "=" * 50)
print("CLEANED DATA")
print("=" * 50)
print(df)

print("\n" + "=" * 50)
print("DATA CLEANING SUMMARY")
print("=" * 50)
print(f"Total Records After Cleaning: {len(df)}")
print(f"Invalid Emails Found: {(~df['Email_Valid']).sum()}")
print("Cleaned dataset saved as 'cleaned_data.csv'")